### ISSUE TITLE
transaction sensors report "unknown"

### ISSUE THREAD

**Issue by jvtwout** [leeyuentuen/alfen_wallbox#183]
Since a while I'm missing al the transaction sensors. All are report "unknown" values. the firmware of the Alfen is: Firmware: 7.1.0-4339, the integration version: 2.9.3. Any suggestion how to solve this?
![Screenshot 2025-01-14 at 14 17 29](https://github.com/user-attachments/assets/81b461da-4865-4480-b8c9-6c5a1ec1d218)

**Comment by leeyuentuen** [comment]
I also notice this issue at my side, i'll later check them

**Comment by fiorentino77** [comment]
Same issue here.
I've tried to re-install integration but without success.

**Comment by barthoefs** [comment]
![image](https://github.com/user-attachments/assets/f4a4972e-f324-4f35-a30a-c79566fddaeb)
Enable transactions...

**Comment by jvtwout** [comment]
I've tried that, but I get an error message when trying to enable the transactions. After submitting twice the error message dissapears, but after a restart of HA the transactions are out of the configuration. :(
![Screenshot 2025-01-15 at 11 27 04](https://github.com/user-attachments/assets/66935a6e-488e-4b09-9cdf-2670a505f91b)

**Comment by barthoefs** [comment]
I had it working with 6.6.0 fw and 2.9.2-rc. But after updating to 7.1.0 I cant connect anymore...

**Comment by MichaelSoe** [comment]
I'm having the exact same issue. Also when trying to enable `transactions` in the settings I get the same error message.

**Comment by jvtwout** [comment]
Just upgrade the Alfen to: Firmware: 7.1.3-4342, but problem is still there.

**Comment by Tanfoglio** [comment]
> I've tried that, but I get an error message when trying to enable the transactions. After submitting twice the error message dissapears, but after a restart of HA the transactions are out of the configuration. :( ![Screenshot 2025-01-15 at 11 27 04](https://github.com/user-attachments/assets/66935a6e-488e-4b09-9cdf-2670a505f91b)

Exactly the same behaviour here.

**Comment by leeyuentuen** [comment]
[2.9.3-beta.4](https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.9.3-beta4) should fix this problem.

**Comment by jvtwout** [comment]
Thanks, fixed the problem!

**Comment by jvtwout** [comment]
For some wheir reason the problem came back.... :( no it's also not possible to disable Solar Charging boost anymore. Any suggestion what this could be?

**Comment by leeyuentuen** [comment]
> For some wheir reason the problem came back.... :( no it's also not possible to disable Solar Charging boost anymore. Any suggestion what this could be? Could the latest core update cause this problem?

Maybe install previous version and see if it still exists.
